class AuthError(Exception):
    """Permission check failed"""
